# Generated by Django 5.2.6 on 2025-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers_remove_user_sity_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number",
                max_length=35,
                null=True,
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
