# Generated by Django 5.2.6 on 2025-10-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_payment_url_payment_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
