# Generated by Django 5.2.6 on 2025-10-10 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Last Updated"
            ),
        ),
    ]
