# Generated by Django 5.2.6 on 2025-09-27 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0002_alter_lesson_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="lesson_image",
        ),
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lesson_previews/",
                verbose_name="Lesson Image",
            ),
        ),
    ]
