# Generated by Django 5.2.6 on 2025-10-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0003_remove_lesson_lesson_image_lesson_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["-id"],
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
    ]
